FROM openjdk:8-alpine
MAINTAINER Nanoo (arnaudlaval33@gmail.com)
ADD target/api-batch-0.0.1-SNAPSHOT.jar api-batch-0.0.1-SNAPSHOT.jar-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","api-batch-0.0.1-SNAPSHOT.jar.jar"]