FROM openjdk:8-alpine
MAINTAINER Nanoo (arnaudlaval33@gmail.com)
ADD target/ms-account-0.0.1-SNAPSHOT.jar ms-account-0.0.1-SNAPSHOT.jar
EXPOSE 9001
ENTRYPOINT ["java","-jar","ms-account-0.0.1-SNAPSHOT.jar"]