FROM openjdk:8
MAINTAINER Nanoo (arnaudlaval33@gmail.com)
ADD target/server-eureka-0.0.1-SNAPSHOT.jar server-eureka-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","server-eureka-0.0.1-SNAPSHOT.jar"]