spring:
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: http://localhost:9100
          predicates:
            - Path = /server-authentication/**
        - id  : book
          uri : http://localhost:9002
          predicates:
            - Path = /ms-book/**
        - id : account
          uri : http://localhost:9001
          predicates:
            - Path = /ms-account/**
        - id : loan
          uri : http://localhost:9003
          predicates:
            - Path = /ms-loan/**




