FROM openjdk:8
MAINTAINER Nanoo (arnaudlaval33@gmail.com)
ADD target/api-client-web-0.0.1-SNAPSHOT.jar api-client-web-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","api-client-web-0.0.1-SNAPSHOT.jar"]