FROM openjdk:8-alpine
MAINTAINER Nanoo (arnaudlaval33@gmail.com)
ADD target/server-authentication-0.0.1-SNAPSHOT.jar server-authentication-0.0.1-SNAPSHOT.jar
EXPOSE 9100
ENTRYPOINT ["java","-jar","server-authentication-0.0.1-SNAPSHOT.jar"]